# Generated by Django 4.0.6 on 2022-07-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='vote',
            field=models.CharField(blank=True, choices=[('1', 'Shreya Ananad'), ('2', 'Shubham Upadhyay'), ('3', 'Raashid Altaf')], max_length=2, null=True),
        ),
    ]
